In [1]:
import numpy as np
 #
간단한

배열

만들기
numbers = np.array([1, 2, 3, 4, 5])
 print("
평균
:", np.mean(numbers))
 print("
합계
:", np.sum(numbers))
 # 2
차원

배열
 (
행렬
)
만들기

matrix = np.array([[1, 2], [3, 4]])
 print("
행렬
:\n", matrix)

IndentationError: unexpected indent (ipython-input-2004551201.py, line 9)

In [3]:
import numpy as np

In [7]:
numbers = np.array([1, 2, 3, 4, 5])
 print("평균:", np.mean(numbers))
 print("합계:", np.sum(numbers))

평균: 3.0
합계: 15


In [8]:
import numpy as np

In [9]:
numbers = np.array([1, 2, 3, 4, 5])

In [14]:
numbers

array([1, 2, 3, 4, 5])

NumPy는 배열 조작, 수학 연산, 통계 계산 등을 위한 다양한 메소드를 제공합니다. 다음은 일반적으로 사용되는 몇 가지 메소드와 예시입니다.

In [16]:
import numpy as np

# NumPy 배열 생성
arr = np.array([1, 2, 3, 4, 5])

# 기본 수학 연산
print("배열 + 2:", arr + 2)
print("배열 * 3:", arr * 3)

# 통계 메소드
print("평균:", np.mean(arr))
print("합계:", np.sum(arr))
print("표준 편차:", np.std(arr))
print("최대값:", np.max(arr))
print("최소값:", np.min(arr))

# 배열 재구성 (Reshaping)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print("원본 행렬:\n", matrix)
print("재구성된 행렬 (2x3에서 3x2로):\n", matrix.reshape(3, 2))

# 배열 연결 (Concatenation)
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
print("연결된 배열:", np.concatenate((arr1, arr2)))

# 배열 정렬 (Sorting)
unsorted_arr = np.array([5, 2, 8, 1, 9])
print("정렬된 배열:", np.sort(unsorted_arr))

배열 + 2: [3 4 5 6 7]
배열 * 3: [ 3  6  9 12 15]
평균: 3.0
합계: 15
표준 편차: 1.4142135623730951
최대값: 5
최소값: 1
원본 행렬:
 [[1 2 3]
 [4 5 6]]
재구성된 행렬 (2x3에서 3x2로):
 [[1 2]
 [3 4]
 [5 6]]
연결된 배열: [1 2 3 4]
정렬된 배열: [1 2 5 8 9]


이것들은 몇 가지 예시일 뿐입니다. NumPy는 다양한 작업을 위한 훨씬 더 많은 메소드를 제공합니다. 전체 목록과 자세한 설명은 공식 NumPy 문서를 참고하세요.

혹시 특정 NumPy 메소드에 대해 더 알고 싶으시거나 다른 예시를 보고 싶으신가요?

In [17]:
zeronumbers=np.zeros()

TypeError: zeros() missing required argument 'shape' (pos 0)

In [18]:
numbers[-2]

np.int64(4)

In [21]:
matrix = np.array([[1, 2], [3, 4]])
 print("행렬:\n", matrix)

IndentationError: unexpected indent (ipython-input-1184902599.py, line 2)

In [22]:
import pandas as pd

In [38]:
students = pd.DataFrame({
   '이름': ['김철수', '이영희', '박민수'],
   '수학': [85, 92, 78],
   '영어': [78, 85, 90]
 })

In [26]:
pd. print(1,0)

AttributeError: module 'pandas' has no attribute 'print'

In [39]:
import numpy as np

In [41]:
 import matplotlib.pyplot as plt

In [42]:
from sklearn.linear_model import LinearRegression

In [44]:
공부시간 = np.array([1, 2, 3, 4, 5, 6, 7, 8]).reshape(-1, 1)

In [46]:
시험점수 = np.array([50, 55, 65, 70, 75, 85, 90, 95])

In [52]:
print("훈련 데이:")
for i in range(len(공부시간)):print(f"공부시간: {공부시간[i][0]}시간 → 점수: {시험점수[i]}점")

훈련 데이:
공부시간: 1시간 → 점수: 50점
공부시간: 2시간 → 점수: 55점
공부시간: 3시간 → 점수: 65점
공부시간: 4시간 → 점수: 70점
공부시간: 5시간 → 점수: 75점
공부시간: 6시간 → 점수: 85점
공부시간: 7시간 → 점수: 90점
공부시간: 8시간 → 점수: 95점


In [55]:
model = LinearRegression()
model.fit(공부시간, 시험점수)

LinearRegression()

In [63]:
새로운_시간 = np.array([[9]])

In [64]:
예측_점수 = model.predict(새로운_시간)

In [65]:
예측_점수

array([102.85714286])